core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.verse.urls')),
    path('users/', include('apps.users.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_URL)

apps/users/forms.py
from django import forms
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    name = forms.CharField(
        label='Почта',
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control input-lg'}),
    )

    email = forms.CharField(
        label='Почта',
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control input-lg'}),
    )
    password = forms.CharField(
        label='Пароль',
        max_length=128,
        required=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control input-lg'}),
    )
    login = forms.CharField(
        label='Пароль',
        max_length=128,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control input-lg'}),
    )
    def clean_email(self):
        login = self.cleaned_data.get('login')

        if not login:
            raise ValidationError('Обязательное поле')

        return login

    def clean_password(self):
        password = self.cleaned_data.get('password')

        if not password:
            raise ValidationError('Обязательное поле')

        return password

templates/pages/author_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Author</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Underdog&display=swap"
      rel="stylesheet"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Ruslan+Display&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/author.css' %}" />
  </head>
  <body>
    <header class="header">

      <div class="bg__author" style="background-image:{% static 'img/author__bg-author.svg' %};">
        <span class="author__text-title">Авторы</span>
      </div>

      <div class="container"></div>
    </header>
    <section class="populars">
      <div class="container">
        <div class="popular">
          <div class="popular__title">
            <h1 class="popular__title-text">Популярные авторы</h1>
          </div>
          <div class="populars__blocks">
            <div class="populars__block">
              <div class="popular__boxs">
                <div class="popular__box-user">
                  <img
                    class="popular__img"
                    src="{% static 'img/popular__box.svg' %}"
                    alt=""
                  />
                  <div class="about__author">
                    <span class="name__users">Саякбай каралаев</span>
                    <p class="about__users">
                      лирика, трагедия, стихи на платформе с 02.07.2021
                    </p>
                  </div>
                </div>
                  {% for authors in popular_authors %}
                  {% if forloop.counter|divisibleby:2 %}
                      <a href="{% url 'author_detail' pk=authors.id %}">
                         <div class="popular__box">
                             <span class="popular__name">{{ authors }} {{ authors.category }} {{ authors.user.date_joined }}</span>
                         </div>
                      </a>
                  {% else %}
                      <a href="{% url 'author_detail' pk=authors.id %}">
                        <div class="popular__box">
                            <span class="popular__name">{{ authors }} {{ authors.category }} {{ authors.date_joined }}</span>
                        </div>
                      </a>
                  {% endif %}
                  {% endfor %}
              </div>
              <div class="popular__boxs">
                <div class="popular__box"></div>
                <div class="popular__box popular__box-deg"></div>
                <div class="popular__box"></div>
              </div>
              <div class="popular__links">
                <a href="#" class="popular__link">Стать автором</a>
              </div>
            </div>
            <div class="popular__symbol">
                <a href="#" class="popular__allauthor">Все авторы</a>

            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="all">
                <h2 class="all__title">Все авторы</h2>
                <div class="all__search">
                    <input placeholder="Поиск" id="author_search_input_id" type="text" class="all__input">
                    <div class="all__search-icon">
                        <img src="{% static 'img/search__icon.png' %}" alt="" class="search-icon">
                    </div>
                </div>
                <div class="all__content">
                    <div class="all__blocks">
                        <div class="all__block">
                            <p class="all__block-text">Автор</p>
                            <p class="all__block-p">Жанр и дата публикации</p>
                            <span class="all__block-name">Саякбай каралаев</span>
                        </div>
                    <div id="author_search_input_block_id">
                        {% for authors in page_obj %}
                            {% if forloop.counter|divisibleby:2 %}
                             <a href="{% url 'author_detail' pk=authors.id %}">
                                    <div class="all__block-grey">{{ authors }}</div>
                                </a>
                                    {% else %}
                             <a href="{% url 'author_detail' pk=authors.id %}">
                                    <div class="all__block-white">{{ authors }}</div>
                               </a>
                            {% endif %}
                        {% endfor %}
                    </div>
                    </div>
                    <div class="all__symblos">
                        <div class="all__symbols-arrows">
                            {% if page_obj.has_previous %}
                            <div class="all-arrow">
                                <a href="?page={{ page_obj.previous_page_number }}">
                                    <img class="arrow" src="{% static 'img/arrow.png' %}" alt="">
                                </a>
                            </div>
                            {% else %}
                            <div class="all-arrow disabled">
                                <a href="">
                                    <img class="arrow" src="{% static 'img/arrow.png' %}" alt="">
                                </a>
                            </div>
                            {% endif %}
                            {% if page_obj.has_next %}
                            <div class="all-arrow">
                                <a href="?page={{ page_obj.next_page_number }}">
                                    <img class="arrow arrow__deg" src="{% static 'img/arrow.png' %}" alt="">
                                </a>
                            </div>
                            {% else %}
                            <div class="all-arrow disabled">
                                <a href="">
                                    <img class="arrow arrow__deg" src="{% static 'img/arrow.png' %}" alt="">
                                </a>
                            </div>
                            {% endif %}
                        </div>
                        <div class="popular__circles">
                            {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}">
                                <div class="popular__circle"></div>
                            </a>
                            {% else %}
                            <a href="">
                                <div class="popular__circle disabled"></div>
                            </a>
                            {% endif %}
                        <a href="">
                            <div class="popular__circle-big active"></div>
                            {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a>
                        {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">
                            <div class="popular__circle"></div>
                        </a>
                        {% else %}
                        <a href="">
                                <div class="popular__circle disabled"></div>
                        </a>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

  </body>
</html>

{% endblock %}

{% block js %}
<script>
    const authorSearchUrl = '{% url "author_search_list" %}';
</script>
    <script src="{% static 'js/author_search_input.js' %}"></script>
{% endblock %}

templates/pages/author_profile_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--    <link rel="stylesheet" href="{% static 'css/visitor.css' %}" />-->
  <html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Author profile</title>

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Underdog&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>

      <div class="container"></div>
      <div class="author__bg">
        <div class="author__bg-all">
            <img src="{% static 'img/moun.jpg' %}" alt="">
        </div>

        <h1 class="author__name">{{ author }}</h1>
        <button class="author__btn-name">Читать</button>
      </div>
      </div>
      <div class="author__status">
        <div class="author__circle"></div>
        <div class="author__status-title">
          <div class="author__status-texts">
            <p class="author__status-text">Произведения</p>
            <span class="author__status-quantity">{{ verse_count.all.count }}</span>
          </div>
          <div class="author__status-texts">
            <p class="author__status-text">
              лайки
            </p>
            <span class="author__status-quantity">{{ like_count.all.count }}</span>
          </div>
          <div class="author__status-texts">
            <p class="author__status-text">читатели</p>
            <span class="author__status-quantity">{{ readers_count.all.count }}</span>
          </div>
        </div>
        <button class="author__status-btn" onclick="toggle()">Читать</button>
      </div>
    </header>
    <section class="creation container">
      <h1 class="creation__h1">произведения</h1>
      <div class="creation__serch">
        <input placeholder="Поиск" type="text" class="creation__inp" />
        <span class="creation__serch-badge">
          <img class="search__badge" src="{% static 'img/search__icon.png' %}" alt="search__badge" />
        </span>
      </div>
    <div class="creations__title">
      <div class="creation__strings">
        <div class="creation__string-names">
          <p class="creation__string-title">Название произведения</p>
          <p class="creation__name-data">Жанр и дата публикации</p>
          <p class="creation__string-name">Саякбай каралаев</p>
        </div>
          {% for verse in detail_author_verses %}
            {% if forloop.counter|divisibleby:2 %}
                <a href="{% url 'verse_detail_view' pk=verse.pk %}">
                <div class="creation__string-grey">{{ verse.name }} {{ verse.category }} {{ verse.pubdate }} {{ verse.author}}</div>
                </a>
          {% else %}
                <a href="{% url 'verse_detail_view' pk=verse.pk %}">
                <div class="creation__string-white">{{ verse.name }} {{ verse.category }} {{ verse.pubdate }} {{ verse.author}}</div>
                </a>
            {% endif %}
            {% endfor %}
      </div>
      <div class="crearions__arrows">
        <div class="creation__arrow">
            {% if page_obj.has_previous %}
              <div class="creation__left">
                <a href="?page={{ page_obj.previous_page_number }}">
                    <img src="{% static 'img/arrow.png' %}" alt="left" class="arrow" />
                </a>
              </div>
            {% else %}
            <div class="creation__left disabled">
                <a href="">
                    <img src="{% static 'img/arrow.png' %}" alt="left" class="arrow" />
                </a>
              </div>
            {% endif %}
            {% if page_obj.has_next %}
              <div class="creation__rigth">
                 <a href="?page={{ page_obj.next_page_number }}"><img
                  src="{% static 'img/arrow.png' %}"
                  alt="right"
                  class="arrow arrow__right"
                /></a>
              </div>
            {% else %}
                <div class="creation__rigth disabled">
                         <a href=""><img
                          src="{% static 'img/arrow.png' %}"
                          alt="right"
                          class="arrow arrow__right"
                        /></a>
                      </div>
            {% endif %}

        </div>
        <div class="creation__circles">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">
                <div class="creation__circle"></div>
            </a>
            {% else %}
            {% endif %}
            <a href="">
                <div class="creation__circle-big">
                </div>{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">
                <div class="creation__circle"></div>
            </a>
        {% else %}

        {% endif %}

        </div>
      </div>
    </div>
  </section>

  </body>



{% endblock %}
{% block js %}
    <script>
        const authorDetailUrl = '{% url "author_detail" author.pk %}';
        const authorId = '{{ author.id }}';
    </script>
    <script src="{% static 'js/author_profile_list.js' %}"></script>
{% endblock %}

templates/pages/authorization.html
<!--{% extends 'base.html' %}-->
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/authorization.css' %}">
    <title>Войти</title>
</head>

<body>
    <img src="{% static 'img/header_bg.png' %}" class="bg" alt="">
    <div class="form">

        <form action="">
            <div class="login_title">Войти в аккаунт</div>
            <input class="login" id="id_login" type="text" placeholder="Логин">
            <input type="password" id="id_password" class="password" placeholder="Пароль">
            <div class="forget_password">Забыли пароль? <a href="#">Восстановление пароля</a></div>
            <button class="login_btn" id="login_btn_id">Войти</button>
            <p id="login_error_block_id" style="display: none; color: red; font-size: 13px; margin-left: 10px">Логин или пароль не правильно введены!</p>
            <div class="forget_password">Нету аккаунта? <a href="{% url 'register' %}">Зарегистрироваться</a></div>
        </form>
    </div>

</body>

{% endblock %}

<script>
        function getCookie(name) {
            let cookieValue = null;

            if (document.cookie && document.cookie !== '') {
                let cookies = document.cookie.split(';');
                console.log(cookies);
                for (let i = 0; i < cookies.length; i++) {
                    let cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }

            return cookieValue;
        };
    </script>

    <script>
        const loginUrl = "{% url 'login' %}";
        const token = getCookie(name='csrftoken');
    </script>
    <script src="{% static 'js/login.js' %}"></script>

templates/pages/base1.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
{% block content %}
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Underdog&display=swap"
      rel="stylesheet"
    />
      {% block css %}
    <link rel="stylesheet" href="{% static 'css/authordashboard.css' %}'" />
      {% endblock %}
  </head>
  <body>
    <header class="header">
      <nav class="nav">
        <div class="container">
          <div class="burger_menu ">
            <div class="burger_content">
                <div class="burger_buttons">
                    <a href="#" class="login_btn-burger">Вход > </a>
                    <a href="#" class="registr_btn-burger">Регистрация > </a>
                </div>
                <a href="#" class="burger_link">Главная</a>
                <a href="#" class="burger_link">Авторы</a>
                <a href="#" class="burger_link">Произведения</a>
                <a href="#" class="burger_link">Новости</a>
            </div>
            <div class="burger_bg burger_close"></div>
        </div>
          <div class="items">
            <div class="logo__img">
              <img src="{% static 'img/logo_white.svg' %}" alt="" class="logo__img-main logo-white">
              <img class="logo__img-main" src="{% static 'img/logo.svg' %}" alt="logo" />
            </div>
            <a href="" class="link">Главная</a>
            <a href="./author.html" class="link">Авторы</a>
            <a href="./works.html" class="link">Произведения</a>
            <a href="" class="link">Новости</a>
            <div class="sign">
              <button class="signup btnup">Вход ></button>
              <button class="checkin btnup">Регистрация ></button>
            </div>
            <div class="burger">
              <div class="burger__line"></div>
              <div class="burger__line burger__line-center "></div>
              <div class="burger__line"></div>
          </div>
          </div>
        </div>
      </nav>
      <div id="bg-avatar" class="header__bg-photo">
        <div class="container">
          <div class="items__user">
            <div class="items__texts">
              <p class="items__text">
                Загрузите фоновое <br />
                изображение
              </p>
              <input type="file" name="file" id="input__filed" class="input input__file-bg">
                <label for="input__filed">
                <span class="input__file-button-text">Выбрать</span>
                </label>
            </div>
            <div class="inp-bg-btn inp-circle-file">
              <input type="file" name="file" id="input__filed" class="input input__file">
              <label for="input__filed">
                <span class="inp-avatar input__file-button-text">
                   <img class="btn__photo" src="{% static 'img/photo-user.svg' %}" alt="Choose photo">
                </span>
              </label>
            </div>
            <div class="items__name">
              <span class="item__name">саякбай каралаев</span>
            </div>
          </div>
          <div id="avatar" class="items__circle">
            <div class="inp-circle-file">
                <input type="file" name="file" id="input__file" class="input input__file">
                <label for="input__file">
                  <span class="inp-avatar input__file-button-text">
                     <img class="btn__photo" src="{% static 'img/photo-user.svg' %}" alt="Choose photo">
                  </span>
                </label>
              </div>
            <div class="items__user">
              <div class="items__texts user__photo">
                <p class="items__text items__ucer-text">
                  Загрузите изображение
                </p>
                <input type="file" name="file" id="input__file" class="input-12 input__file">
                <label for="input__file">
                <span class="input__file-button-text">Выбрать</span>
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="statistics">
        <div class="container">
          <div class="statistics__user">
            <div class="statistic">
              <p class="statistic__text-num">Произведения</p>
              <span class="statistic__text-num">274</span>
            </div>
            <div class="statistic">
              <p class="statistic__text-num">Лайки</p>
              <span class="statistic__text-num">8562</span>
            </div>
            <div class="statistic">
              <p class="statistic__text-num">читатели</p>
              <span class="statistic__text-num">427 895</span>
            </div>
          </div>
        </div>
      </div>
    </header>
    <section class="creations container">
      <h1 class="creation__h1">мои произведения</h1>
      <div class="creation__serch">
        <input placeholder="Поиск" type="text" class="creation__inp" />
        <span class="creation__serch-badge">
          <img class="serch-badge" src="{% static 'img/search__icon.png' %}" alt="search__badge" />
        </span>
      </div>
      <div class="creations__title">
        <div class="creation__strings">
          <div class="creation__string-names">
            <p class="creation__string-title">Название произведения</p>
            <p class="creation__name-data">Жанр и дата публикации</p>
            <p class="creation__string-name">Саякбай каралаев</p>
          </div>
          <div class="creation__string-grey"></div>
          <div class="creation__string-white"></div>
          <div class="creation__string-grey"></div>
          <div class="creation__string-white"></div>
          <div class="creation__string-grey"></div>
          <div class="creation__string-white"></div>
          <div class="creation__string-grey"></div>
        </div>
        <div class="crearions__arrows">
          <div class="creation__arrow">
            <div class="creation__left">
              <img src="{% static 'img/arrow.png' %}" alt="left" class="arrow" />
            </div>
            <div class="creation__rigth">
              <img
                src="{% static 'img/arrow.png' %}"
                alt="right"
                class="arrow arrow__right"
              />
            </div>
          </div>
          <div class="creation__circles">
            <div class="creation__circle-big"></div>
            <div class="creation__circle"></div>
            <div class="creation__circle"></div>
            <div class="creation__circle"></div>
            <div class="creation__circle"></div>
            <div class="creation__circle"></div>
          </div>
        </div>
      </div>
    </section>
    <section class="publish container">
      <h2 class="publish__h2">Опубликовать произведение</h2>
      <div class="publish__blocks">
        <div class="publish__block-big">
          <p class="block__text">Произведение</p>
          <textarea class="block__in-big"></textarea>
        </div>
        <div class="publish__btm-o">
        <div class="publish__block">
          <div class="publish__block-in">
            <p class="block__in-none-text">Названия</p>
            <textarea class="block__in-none"></textarea>
            </div>
          <div class="publish__block-in">
          <p class="block__text">Иллюстрация</p>
          <div id="com-bg" class="block__in">
            <div id="publish-btn" class="inp-bg-btn inp-circle-file">
              <input type="file" name="file" id="input__file-com" class="input input__file">
              <label for="input__file-com">
                <span class="inp-avatar input__file-button-text">
                   <img class="btn__photo" src="{% static 'img/photo-user.svg' %}" alt="Choose photo">
                </span>
              </label>
            </div>
            <div class="items__texts block__items-texts">
              <p class="items__text items__ucer-text">
                Загрузите изображение
              </p>
              <input type="file" name="file" id="input__file-com" class="input input__file-com">
                <label for="input__file-com">
                <span class="input__file-button-text">Выбрать</span>
                </label>
            </div>
          </div>
        </div>

        </div>
        <div class="publish__block block__in-bottom">
          <div class="publish__block-min">
          <p class="block__text">Описание</p>
          <textarea class="block__in block-in"></textarea>
        </div>
        <div class="publish__block-min">
          <p class="block__text block__text-bottom">Хештеги</p>
          <textarea class="block__in block__in-end"></textarea>
          <p class="block__text block__text-bottom">Жанр</p>
          <select class="block__select" name="" id="">
            <option>Художественное</option>
            <option>Драма</option>
            <option>Биография</option>
          </select>
          <button class="item__btn block__btn">опубликовать</button>
        </div>
      </div>
    </div>
      </div>
    </section>
    <footer class="footer">
      <div class="container">
          <div class="footer__links">
              <div class="footer__link">
                  <a href="#" class="footer__link-a">Авторы</a>
                  <a href="#" class="footer__link-a">Популярные авторы</a>
                  <a href="#" class="footer__link-a">Все авторы</a>
                  <a href="#" class="footer__link-a">Стать автором</a>
              </div>
              <div class="footer__link">
                  <a href="#" class="footer__link-a">Произведения</a>
                  <a href="#" class="footer__link-a">Популярные произведения </a>
                  <a href="#" class="footer__link-a">Все произведения </a>
                  <a href="#" class="footer__link-a">Поделиться произведением</a>
              </div>
              <div class="footer__link footer__link-btm">
                  <a href="#" class="footer__link-a">Новости</a>
                  <a href="#" class="footer__link-a">Статистика</a>
                  <a href="#" class="footer__link-a">Выбор редакции</a>
                  <a href="#" class="footer__link-a">История кыргызкой литературы</a>
              </div>
              <div class="footer__link footer__link-btm">
                  <a href="#" class="footer__link-a">О нас</a>
                  <a href="#" class="footer__link-a">Войти</a>
                  <a href="#" class="footer__link-a">Зарегистрироваться</a>
              </div>
          </div>
          <div class="socials">
              <span class="social__link">Политика конфиденциальности</span>
              <div class="social__icons">
                  <a href="" class="social__link">Социальные сети</a>
                  <div class="cocial__icon">
                      <img class="social__icon-img" src="{% static 'img/instagram.png' %}" alt="Instagram">
                      <img class="social__icon-img" src="{% static 'img/twitter.png' %}" alt="Twitter">
                      <img class="social__icon-img" src="{% static 'img/youtube.png' %}" alt="YouTube">
              </div>
          </div>
      </div>
  </footer>





  <script src="./burger.js"></script>
  <script src="./file.js"></script>
  </body>
</html>
{% endblock %}

templates/pages/politics.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/politics.css' %}">

<body>
    <div class="title">Политика конфиденциальности</div>
    <div class="text">Политика конфиденциальности</div>
</body>

{% endblock %}